export const GET_TASKS_LOADING = "GET_TASKS_LOADING";
export const GET_TASKS_SUCCESS = "GET_TASKS_SUCCESS";
export const GET_TASKS_ERROR = "GET_TASKS_ERROR";

export const GET_TASK_WITH_DRAFT_LOADING = "GET_TASK_WITH_DRAFT_LOADING";
export const GET_TASK_WITH_DRAFT_SUCCESS = "GET_TASK_WITH_DRAFT_SUCCESS";
export const GET_TASK_WITH_DRAFT_ERROR = "GET_TASK_WITH_DRAFT_ERROR";

export const ADD_EDIT_TASK_CANCELLED = "ADD_EDIT_TASK_CANCELLED";

export const SAVE_TASK_LOADING = "SAVE_TASK_LOADING";
export const SAVE_TASK_SUCCESS = "SAVE_TASK_SUCCESS";
export const SAVE_TASK_ERROR = "SAVE_TASK_ERROR";
